import Head from 'next/head';
import { Header } from '../components/Header';
import { Login } from '../components/Login';
import { getSession } from 'next-auth/client';
import { SideBar } from '../components/SideBar';
import { Feed } from '../components/Feed';

export default function Home({ session }) {
	if (!session) return <Login />;
	return (
		<div className='h-screen bg-gray-100 overflow-hidden'>
			<Head>
				<title>Facebook Clone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			<main className='flex'>
				<SideBar />
				<Feed />
			</main>
		</div>
	);
}

export async function getServerSideProps(context) {
	const session = await getSession(context);

	return {
		props: {
			session,
		},
	};
}
